// importScripts("https://cdn.pushalert.co/sw-77397_2.js");
var comm_url = "https://request.pushalert.co/";
var default_title = "";
var default_message = "";
var default_icon = "https://cdn.pushalert.co/img/pushalert-square-icon.png";
var default_url = "https://y3seker.github.io/visapush";
var last_updated = "1733569947";
var client_id = 76192;
var domain_id = 2;
var pa_subdomain = "https://y3seker349.pushalert.co";
var appPublicKey = 'BE/ri8JsMfuc3Z22KSMKUAO33c3odtoUGcIICcmGyRISbcMrbwu6UqN2W8LDx4tzLSPUArz7vvO5/eVXYCs9dY8=';
importScripts("https://cdn.pushalert.co/sw-external-payload.js?t="+last_updated);